---
title: 'Exploring Distributions'
author: "STA 310: Homework 2"
output: pdf_document
---

# Instructions

-   Write all narrative using full sentences. Write all interpretations and conclusions in the context of the data.
-   Be sure all analysis code is displayed in the rendered pdf.
-   If you are fitting a model, display the model output in a neatly formatted table. (The `tidy` and `kable` functions can help!)
-   If you are creating a plot, use clear and informative labels and titles.
-   Render and back up your work reguarly, such as using Github.
-   When you're done, we should be able to render the final version of the Rmd document to fully reproduce your pdf.
-   Upload your pdf to Gradescope. Upload your Rmd, pdf (and any data) to Canvas.

These exercises come from BMLR or are adapted from BMLR, Chapter 3.

# Exercises

## Exercise 1

At what value of $p$ is the variance of a binary random variable smallest? When is the variance the largest? Back up your answer empirically or mathematically.

> For a binary random variable X, that takes on the values 0 and 1, there are two possible probability outcomes: $p$, the probability of a success, and \$(1-p), the probability of a failure. Therefore the expectation of this binary random variable is equal to $E[X] = 1(p) + 0(1-p) = p$. The second moment is equal to: $E[X^2] = 1^2(p) + 0^2(1-p) = p$. The variance is therefore equal to: $Var(X) = E[X^2] - (E[X])^2 = p - (p)^2 = p - p^2$. Since this is a negative quadratic function, we can find that the maximum is at the vertex, when p = 0.5, with a variance of 0.25. Since the variance is bounded by the constraints that $0 <= p <= 1$, we can calculate that the minimum is either when p = 0 or when p = 1. After calculating both points, we can see that the minimum is when p = 0 or p = 1, with a variance of 0 for both values of p.

## Exercise 2

How are hypergeometric and binomial random variables different? How are they similar?

> A binomial random variable represents the number of successes in a fixed number of trials, with replacement. A hypergeometric variable represents the number of successes in a fixed number of trials, without replacement. They are similar in that they both represent the number of successes in a fixed number of trials, the only difference is that one uses replacement and the other does not.

## Exercise 3

How are exponential and Poisson random variables related?

> An exponential random variable represents the time between two events in a Poisson process. A poisson random variable represents the number of events in a fixed period of time.

## Exercise 4

How are geometric and exponential random variables similar? How are they different?

> Geometric random variables represent the number of trials required to get to the first success of a Bernoulli trial. Exponential random variables represent the time between two events/trials. They are similar in that they both depend on the first occurrence or success in a process. They are similar in that exponential variables represent time (continuous) while geometric variables represent a number of trials (discrete).

## Exercise 5

A university's college of sciences is electing a new board of 5 members. There are 35 applicants, 10 of which come from the math department. What distribution could be helpful to model the probability of electing $X$ board members from the math department?

> A hypergeometric distribution could be helpful to model the probability of electing $X$ board members from the math department. This is because this process can be represented by the probability of $X$ successes in a fixed number of trials (5), without replacement (since no member can be chosen twice.)

## Exercise 6

Chapter 1 asked you to consider a scenario where *"The Minnesota Pollution Control Agency is interested in using traffic volume data to generate predictions of particulate distributions as measured in counts per cubic feet."* What distribution might be useful to model this count per cubic foot? Why?

> We can use a Poisson distribution. We can use a Poisson distribution to model the model the occurrences of an event, distributed across a randomly distributed space. Poisson distributions are often used to model the number of bacteria in a specific area, and similarly, we can use the Poisson distribution to model the counts per cubic feet of particulate distributions across a specific area (one cubic foot).

**DOUBLE CHECK THIS**

## Exercise 7

Chapter 1 also asked you to consider a scenario where *"Researchers are attempting to see if socioeconomic status and parental stability are predictive of low birthweight. They classify a low birthweight as below 2500 g, hence our response is binary: 1 for low birthweight, and 0 when the birthweight is not low."* What distribution might be useful to model if a newborn has low birthweight?

> We can use a Bernoulli distribution. In a Bernoulli distribution, we model the probability of an event, where there are only two outcomes, a success and failure. We can model the scenario above because the outcome is binary (1 or 0) and a success would be low birth weight and a failure would be not low birth weight.

## Exercise 8

Chapter 1 also asked you to consider a scenario where *"Researchers are interested in how elephant age affects mating patterns among males. In particular, do older elephants have greater mating success, and is there an optimal age for mating among males? Data collected includes, for each elephant, age and number of matings in a given year."* Which distribution would be useful to model the number of matings in a given year for these elephants? Why?

> We can use a Poisson distribution. In a Poisson distribution, we are counting the number of events in a given amount of time. Similarly in this scenario, we are modeling the number of matings in a given year for elephants, so the Poisson distribution works best.

## Exercise 9

Describe a scenario which could be modeled using a gamma distribution.

> The gamma distribution is used to model the time between multiple events in a Poisson process. One example could be one similar to that of Exercise 8, where researchers want to know how long it takes for elephants to have 5 matings. In this scenario, we could use a gamma distribution to model the time before 5 matings in the elephants in the given sample.

**DOUBLE CHECK**

## Exercise 10

**Beta-binomial distribution.** We can generate more distributions by mixing two random variables. \index{mixture model} Beta-binomial random variables are binomial random variables with fixed $n$ whose parameter $p$ follows a beta distribution with fixed parameters $\alpha, \beta$. In more detail, we would first draw $p_1$ from our beta distribution, and then generate our first observation $y_1$, a random number of successes from a binomial ($n, p_1$) distribution. Then, we would generate a new $p_2$ from our beta distribution, and use a binomial distribution with parameters $n, p_2$ to generate our second observation $y_2$. We would continue this process until desired.

Note that all of the observations $y_i$ will be integer values from $0, 1, \ldots, n$. With this in mind, use `rbinom()` to simulate 1,000 observations from a plain old vanilla binomial random variable with $n=10$ and $p=0.8$. Plot a histogram of these binomial observations. Then, do the following to generate a beta-binomial distribution:

a.  Draw $p_i$ from the beta distribution with $\alpha=4$ and $\beta=1$.
b.  Generate an observation $y_i$ from a binomial distribution with $n=10$ and $p = p_i$.
c.  Repeat (a) and (b) 1,000 times ($i=1,\ldots,1000$).
d.  Plot a histogram of these beta-binomial observations.

Compare the histograms of the "plain old" binomial and beta-binomial distributions. How do their shapes, standard deviations, means, possible values, etc. compare?

```{r message=FALSE}
library(tidyverse)

set.seed(310)

binom <- rbinom(1000, 10, 0.8)
binom |>
  tibble() |>
  rename("Observation" = `binom`) |>
  ggplot(aes(x = Observation)) +
  geom_histogram(binwidth = 1,
                 color = "black",
                 fill = "lightblue") +
  scale_x_continuous(breaks = seq(1, 10, by = 1)) +
  labs(y = "Count",
       title = "Binomial Distribution")


data <- numeric(length = 1000)

for (i in 1:1000) {
  p_i <- rbeta(1, 4, 1)
  data[i] = rbinom(1, 10, p_i)
}

data |>
  tibble() |>
  ggplot(aes(x = data)) +
  geom_histogram(binwidth = 1,
                 color = "black",
                 fill = "lightblue") +
  scale_x_continuous(breaks = seq(0, 10, by = 1)) +
  labs(x = "Observation",
       y = "Count",
       title = "Beta-Binomial Distribution")

data |>
  sd()

binom |>
  sd()

```

Compare the histograms of the “plain old” binomial and beta-binomial distributions. How do their shapes, standard deviations, means, possible values, etc. compare?

The shape of the plain old binomial distribution looks relatively normally distributed around the mean, 8; however, it is slightly skewed right with a tail on the left side. This distribution does not have any observations of 1-3, and the minimum value is 4.

On the other hand, the beta-binomial distribution is heavily skewed right with a long tail on the left, with a minimum value of 0. The beta-binomial distribution has a higher standard deviation (2.12 compared to 1.27 for binomial distribution). The mode of the beta-binomial distribution is 10, which is much more common than any of the other observations.

They are both similar in that most of the data is contained in the 7-10 range.

# Grading

| **Total**             | **33** |
|-----------------------|:------:|
| Ex 1                  |   5    |
| Ex 2                  |   5    |
| Ex 3                  |   5    |
| Ex 4                  |   5    |
| Ex 5                  |   2    |
| Ex 6                  |   2    |
| Ex 7                  |   2    |
| Ex 8                  |   2    |
| Ex 9                  |   2    |
| Ex 10                 |   5    |
| Workflow & formatting |   3    |

The "Workflow & formatting" grade is to based on the organization of the assignment write up along with the reproducible workflow. This includes having an organized write up with neat and readable headers, code, and narrative, including properly rendered mathematical notation. It also includes having a reproducible Rmd or Quarto document that can be rendered to reproduce the submitted PDF.
